### ISSUE TITLE
pinecone fails when I try to run

### ISSUE THREAD

**Issue by the-spanish-guy** [mvllow/pinecone#11]
Hi! I'm trying to run the pinecone but it returns an error when I pass an argument

![Screenshot_20210120_155826](https://user-images.githubusercontent.com/32144508/105221883-7b4ef380-5b38-11eb-8723-383c3d0c512b.png)
![Screenshot_20210120_155853](https://user-images.githubusercontent.com/32144508/105221931-8b66d300-5b38-11eb-8f88-1f8c9037ed89.png)

I need to do any configuration before running it?

**Comment by mvllow** [comment]
Thank you for reporting 😌 

I just released v1.3.1 https://github.com/mvllow/pinecone/commit/e53609361552ed62ddc01996e0713c7abd8e60e4 which should fix this issue. Let me know if that helps. If not, please reply with your node version (eg. `node --version`)

**Comment by the-spanish-guy** [comment]
I updated and it looks like this release fixed the problem
Thanks
