### ISSUE TITLE
TypeError: Unable to read user config.

### ISSUE THREAD

**Issue by ignism** [mvllow/pinecone#29]
After installing pinecone and run `init` to create a new theme.
I am unable to convert it because it says the config file is invalid.

```
Unable to read "pinecone.config.js". This is likely due to invalid syntax.

file:///usr/local/lib/node_modules/pinecone-cli/dist/config.js:44
            throw new TypeError('Unable to read user config.');

TypeError: Unable to read user config.
    at resolveConfig (file:///usr/local/lib/node_modules/pinecone-cli/dist/config.js:44:19)
    at async pinecone (file:///usr/local/lib/node_modules/pinecone-cli/dist/index.js:7:20)
    at async file:///usr/local/lib/node_modules/pinecone-cli/dist/cli.js:53:1
```

**Comment by mvllow** [comment]
Is `pinecone.config.js` file created? If so, what are the contents?

I am unable to reproduce, trying:

```sh
mkdir new-vscode-theme
cd new-vscode-theme
npx pinecone-cli@latest
```

This creates the following structure:

- new-vscode-theme
  - pinecone.config.js
  - themes/
    - _pinecone-color-theme.json
    - caffe-color-theme.json
    - caffe-latte-color-theme.json

**Comment by mvllow** [comment]
This may be caused by not having `"type": "module"` in your package.json. 

Node should show a similar warning if so:

```
(node:84073) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
```

**Comment by ignism** [comment]
Ah my bad, you're correct. I did need to put the type to module.

Thanks also for the lovely theme, I've been literally trying themes that suit me last couple months and Rose Pine sticks!
